// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: streaming_greet/GreetStreampb/greetStream.proto

package GreetStreampb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetManyTimesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
}

func (x *GreetManyTimesRequest) Reset() {
	*x = GreetManyTimesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streaming_greet_GreetStreampb_greetStream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetManyTimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetManyTimesRequest) ProtoMessage() {}

func (x *GreetManyTimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_greet_GreetStreampb_greetStream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetManyTimesRequest.ProtoReflect.Descriptor instead.
func (*GreetManyTimesRequest) Descriptor() ([]byte, []int) {
	return file_streaming_greet_GreetStreampb_greetStream_proto_rawDescGZIP(), []int{0}
}

func (x *GreetManyTimesRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GreetManyTimesRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type GreetManyTimesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *GreetManyTimesResponse) Reset() {
	*x = GreetManyTimesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streaming_greet_GreetStreampb_greetStream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetManyTimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetManyTimesResponse) ProtoMessage() {}

func (x *GreetManyTimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_greet_GreetStreampb_greetStream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetManyTimesResponse.ProtoReflect.Descriptor instead.
func (*GreetManyTimesResponse) Descriptor() ([]byte, []int) {
	return file_streaming_greet_GreetStreampb_greetStream_proto_rawDescGZIP(), []int{1}
}

func (x *GreetManyTimesResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_streaming_greet_GreetStreampb_greetStream_proto protoreflect.FileDescriptor

var file_streaming_greet_GreetStreampb_greetStream_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x67, 0x72, 0x65, 0x65,
	0x74, 0x2f, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x70, 0x62, 0x2f,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0d, 0x67, 0x72, 0x65, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x70, 0x62,
	0x22, 0x53, 0x0a, 0x15, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4d, 0x61,
	0x6e, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x32, 0x78, 0x0a, 0x15, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x5f, 0x0a, 0x0e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x12, 0x24, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x70, 0x62, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4d, 0x61,
	0x6e, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x42, 0x20, 0x5a, 0x1e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x2f, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_streaming_greet_GreetStreampb_greetStream_proto_rawDescOnce sync.Once
	file_streaming_greet_GreetStreampb_greetStream_proto_rawDescData = file_streaming_greet_GreetStreampb_greetStream_proto_rawDesc
)

func file_streaming_greet_GreetStreampb_greetStream_proto_rawDescGZIP() []byte {
	file_streaming_greet_GreetStreampb_greetStream_proto_rawDescOnce.Do(func() {
		file_streaming_greet_GreetStreampb_greetStream_proto_rawDescData = protoimpl.X.CompressGZIP(file_streaming_greet_GreetStreampb_greetStream_proto_rawDescData)
	})
	return file_streaming_greet_GreetStreampb_greetStream_proto_rawDescData
}

var file_streaming_greet_GreetStreampb_greetStream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streaming_greet_GreetStreampb_greetStream_proto_goTypes = []interface{}{
	(*GreetManyTimesRequest)(nil),  // 0: greetStreampb.GreetManyTimesRequest
	(*GreetManyTimesResponse)(nil), // 1: greetStreampb.GreetManyTimesResponse
}
var file_streaming_greet_GreetStreampb_greetStream_proto_depIdxs = []int32{
	0, // 0: greetStreampb.StreamGreetingService.GreetManyTimes:input_type -> greetStreampb.GreetManyTimesRequest
	1, // 1: greetStreampb.StreamGreetingService.GreetManyTimes:output_type -> greetStreampb.GreetManyTimesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streaming_greet_GreetStreampb_greetStream_proto_init() }
func file_streaming_greet_GreetStreampb_greetStream_proto_init() {
	if File_streaming_greet_GreetStreampb_greetStream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_streaming_greet_GreetStreampb_greetStream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetManyTimesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streaming_greet_GreetStreampb_greetStream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetManyTimesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_streaming_greet_GreetStreampb_greetStream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streaming_greet_GreetStreampb_greetStream_proto_goTypes,
		DependencyIndexes: file_streaming_greet_GreetStreampb_greetStream_proto_depIdxs,
		MessageInfos:      file_streaming_greet_GreetStreampb_greetStream_proto_msgTypes,
	}.Build()
	File_streaming_greet_GreetStreampb_greetStream_proto = out.File
	file_streaming_greet_GreetStreampb_greetStream_proto_rawDesc = nil
	file_streaming_greet_GreetStreampb_greetStream_proto_goTypes = nil
	file_streaming_greet_GreetStreampb_greetStream_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StreamGreetingServiceClient is the client API for StreamGreetingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamGreetingServiceClient interface {
	GreetManyTimes(ctx context.Context, in *GreetManyTimesRequest, opts ...grpc.CallOption) (StreamGreetingService_GreetManyTimesClient, error)
}

type streamGreetingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamGreetingServiceClient(cc grpc.ClientConnInterface) StreamGreetingServiceClient {
	return &streamGreetingServiceClient{cc}
}

func (c *streamGreetingServiceClient) GreetManyTimes(ctx context.Context, in *GreetManyTimesRequest, opts ...grpc.CallOption) (StreamGreetingService_GreetManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StreamGreetingService_serviceDesc.Streams[0], "/greetStreampb.StreamGreetingService/GreetManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamGreetingServiceGreetManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamGreetingService_GreetManyTimesClient interface {
	Recv() (*GreetManyTimesResponse, error)
	grpc.ClientStream
}

type streamGreetingServiceGreetManyTimesClient struct {
	grpc.ClientStream
}

func (x *streamGreetingServiceGreetManyTimesClient) Recv() (*GreetManyTimesResponse, error) {
	m := new(GreetManyTimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamGreetingServiceServer is the server API for StreamGreetingService service.
type StreamGreetingServiceServer interface {
	GreetManyTimes(*GreetManyTimesRequest, StreamGreetingService_GreetManyTimesServer) error
}

// UnimplementedStreamGreetingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStreamGreetingServiceServer struct {
}

func (*UnimplementedStreamGreetingServiceServer) GreetManyTimes(*GreetManyTimesRequest, StreamGreetingService_GreetManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetManyTimes not implemented")
}

func RegisterStreamGreetingServiceServer(s *grpc.Server, srv StreamGreetingServiceServer) {
	s.RegisterService(&_StreamGreetingService_serviceDesc, srv)
}

func _StreamGreetingService_GreetManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetManyTimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamGreetingServiceServer).GreetManyTimes(m, &streamGreetingServiceGreetManyTimesServer{stream})
}

type StreamGreetingService_GreetManyTimesServer interface {
	Send(*GreetManyTimesResponse) error
	grpc.ServerStream
}

type streamGreetingServiceGreetManyTimesServer struct {
	grpc.ServerStream
}

func (x *streamGreetingServiceGreetManyTimesServer) Send(m *GreetManyTimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _StreamGreetingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greetStreampb.StreamGreetingService",
	HandlerType: (*StreamGreetingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetManyTimes",
			Handler:       _StreamGreetingService_GreetManyTimes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "streaming_greet/GreetStreampb/greetStream.proto",
}
