// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: hw_bidirectional_streaming/maxpb/max.proto

package maxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaxStreamIntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *MaxStreamIntRequest) Reset() {
	*x = MaxStreamIntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hw_bidirectional_streaming_maxpb_max_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxStreamIntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxStreamIntRequest) ProtoMessage() {}

func (x *MaxStreamIntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hw_bidirectional_streaming_maxpb_max_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxStreamIntRequest.ProtoReflect.Descriptor instead.
func (*MaxStreamIntRequest) Descriptor() ([]byte, []int) {
	return file_hw_bidirectional_streaming_maxpb_max_proto_rawDescGZIP(), []int{0}
}

func (x *MaxStreamIntRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type MaxStreamIntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *MaxStreamIntResponse) Reset() {
	*x = MaxStreamIntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hw_bidirectional_streaming_maxpb_max_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxStreamIntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxStreamIntResponse) ProtoMessage() {}

func (x *MaxStreamIntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hw_bidirectional_streaming_maxpb_max_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxStreamIntResponse.ProtoReflect.Descriptor instead.
func (*MaxStreamIntResponse) Descriptor() ([]byte, []int) {
	return file_hw_bidirectional_streaming_maxpb_max_proto_rawDescGZIP(), []int{1}
}

func (x *MaxStreamIntResponse) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_hw_bidirectional_streaming_maxpb_max_proto protoreflect.FileDescriptor

var file_hw_bidirectional_streaming_maxpb_max_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x68, 0x77, 0x5f, 0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2f, 0x6d, 0x61, 0x78,
	0x70, 0x62, 0x2f, 0x6d, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x61,
	0x78, 0x70, 0x62, 0x22, 0x2d, 0x0a, 0x13, 0x4d, 0x61, 0x78, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x2e, 0x0a, 0x14, 0x4d, 0x61, 0x78, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x32, 0x65, 0x0a, 0x16, 0x42, 0x69, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x4b, 0x0a, 0x0c,
	0x4d, 0x61, 0x78, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x6d,
	0x61, 0x78, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x78, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x61, 0x78, 0x70, 0x62,
	0x2e, 0x4d, 0x61, 0x78, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21, 0x68, 0x77, 0x5f,
	0x62, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2f, 0x6d, 0x61, 0x78, 0x70, 0x62, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hw_bidirectional_streaming_maxpb_max_proto_rawDescOnce sync.Once
	file_hw_bidirectional_streaming_maxpb_max_proto_rawDescData = file_hw_bidirectional_streaming_maxpb_max_proto_rawDesc
)

func file_hw_bidirectional_streaming_maxpb_max_proto_rawDescGZIP() []byte {
	file_hw_bidirectional_streaming_maxpb_max_proto_rawDescOnce.Do(func() {
		file_hw_bidirectional_streaming_maxpb_max_proto_rawDescData = protoimpl.X.CompressGZIP(file_hw_bidirectional_streaming_maxpb_max_proto_rawDescData)
	})
	return file_hw_bidirectional_streaming_maxpb_max_proto_rawDescData
}

var file_hw_bidirectional_streaming_maxpb_max_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hw_bidirectional_streaming_maxpb_max_proto_goTypes = []interface{}{
	(*MaxStreamIntRequest)(nil),  // 0: maxpb.MaxStreamIntRequest
	(*MaxStreamIntResponse)(nil), // 1: maxpb.MaxStreamIntResponse
}
var file_hw_bidirectional_streaming_maxpb_max_proto_depIdxs = []int32{
	0, // 0: maxpb.BiDirectionalStreaming.MaxStreamInt:input_type -> maxpb.MaxStreamIntRequest
	1, // 1: maxpb.BiDirectionalStreaming.MaxStreamInt:output_type -> maxpb.MaxStreamIntResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hw_bidirectional_streaming_maxpb_max_proto_init() }
func file_hw_bidirectional_streaming_maxpb_max_proto_init() {
	if File_hw_bidirectional_streaming_maxpb_max_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hw_bidirectional_streaming_maxpb_max_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxStreamIntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hw_bidirectional_streaming_maxpb_max_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxStreamIntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hw_bidirectional_streaming_maxpb_max_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hw_bidirectional_streaming_maxpb_max_proto_goTypes,
		DependencyIndexes: file_hw_bidirectional_streaming_maxpb_max_proto_depIdxs,
		MessageInfos:      file_hw_bidirectional_streaming_maxpb_max_proto_msgTypes,
	}.Build()
	File_hw_bidirectional_streaming_maxpb_max_proto = out.File
	file_hw_bidirectional_streaming_maxpb_max_proto_rawDesc = nil
	file_hw_bidirectional_streaming_maxpb_max_proto_goTypes = nil
	file_hw_bidirectional_streaming_maxpb_max_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BiDirectionalStreamingClient is the client API for BiDirectionalStreaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BiDirectionalStreamingClient interface {
	MaxStreamInt(ctx context.Context, opts ...grpc.CallOption) (BiDirectionalStreaming_MaxStreamIntClient, error)
}

type biDirectionalStreamingClient struct {
	cc grpc.ClientConnInterface
}

func NewBiDirectionalStreamingClient(cc grpc.ClientConnInterface) BiDirectionalStreamingClient {
	return &biDirectionalStreamingClient{cc}
}

func (c *biDirectionalStreamingClient) MaxStreamInt(ctx context.Context, opts ...grpc.CallOption) (BiDirectionalStreaming_MaxStreamIntClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BiDirectionalStreaming_serviceDesc.Streams[0], "/maxpb.BiDirectionalStreaming/MaxStreamInt", opts...)
	if err != nil {
		return nil, err
	}
	x := &biDirectionalStreamingMaxStreamIntClient{stream}
	return x, nil
}

type BiDirectionalStreaming_MaxStreamIntClient interface {
	Send(*MaxStreamIntRequest) error
	Recv() (*MaxStreamIntResponse, error)
	grpc.ClientStream
}

type biDirectionalStreamingMaxStreamIntClient struct {
	grpc.ClientStream
}

func (x *biDirectionalStreamingMaxStreamIntClient) Send(m *MaxStreamIntRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *biDirectionalStreamingMaxStreamIntClient) Recv() (*MaxStreamIntResponse, error) {
	m := new(MaxStreamIntResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BiDirectionalStreamingServer is the server API for BiDirectionalStreaming service.
type BiDirectionalStreamingServer interface {
	MaxStreamInt(BiDirectionalStreaming_MaxStreamIntServer) error
}

// UnimplementedBiDirectionalStreamingServer can be embedded to have forward compatible implementations.
type UnimplementedBiDirectionalStreamingServer struct {
}

func (*UnimplementedBiDirectionalStreamingServer) MaxStreamInt(BiDirectionalStreaming_MaxStreamIntServer) error {
	return status.Errorf(codes.Unimplemented, "method MaxStreamInt not implemented")
}

func RegisterBiDirectionalStreamingServer(s *grpc.Server, srv BiDirectionalStreamingServer) {
	s.RegisterService(&_BiDirectionalStreaming_serviceDesc, srv)
}

func _BiDirectionalStreaming_MaxStreamInt_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BiDirectionalStreamingServer).MaxStreamInt(&biDirectionalStreamingMaxStreamIntServer{stream})
}

type BiDirectionalStreaming_MaxStreamIntServer interface {
	Send(*MaxStreamIntResponse) error
	Recv() (*MaxStreamIntRequest, error)
	grpc.ServerStream
}

type biDirectionalStreamingMaxStreamIntServer struct {
	grpc.ServerStream
}

func (x *biDirectionalStreamingMaxStreamIntServer) Send(m *MaxStreamIntResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *biDirectionalStreamingMaxStreamIntServer) Recv() (*MaxStreamIntRequest, error) {
	m := new(MaxStreamIntRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BiDirectionalStreaming_serviceDesc = grpc.ServiceDesc{
	ServiceName: "maxpb.BiDirectionalStreaming",
	HandlerType: (*BiDirectionalStreamingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MaxStreamInt",
			Handler:       _BiDirectionalStreaming_MaxStreamInt_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hw_bidirectional_streaming/maxpb/max.proto",
}
