// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: hw_streaming_number_decomposition/NumberDecompositionpb/decomposition.proto

package NumberDecompositionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumberDecompositionStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *NumberDecompositionStreamRequest) Reset() {
	*x = NumberDecompositionStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberDecompositionStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberDecompositionStreamRequest) ProtoMessage() {}

func (x *NumberDecompositionStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberDecompositionStreamRequest.ProtoReflect.Descriptor instead.
func (*NumberDecompositionStreamRequest) Descriptor() ([]byte, []int) {
	return file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_rawDescGZIP(), []int{0}
}

func (x *NumberDecompositionStreamRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type NumberDecompositionStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *NumberDecompositionStreamResponse) Reset() {
	*x = NumberDecompositionStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberDecompositionStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberDecompositionStreamResponse) ProtoMessage() {}

func (x *NumberDecompositionStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberDecompositionStreamResponse.ProtoReflect.Descriptor instead.
func (*NumberDecompositionStreamResponse) Descriptor() ([]byte, []int) {
	return file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_rawDescGZIP(), []int{1}
}

func (x *NumberDecompositionStreamResponse) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto protoreflect.FileDescriptor

var file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_rawDesc = []byte{
	0x0a, 0x4b, 0x68, 0x77, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x2f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x64,
	0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x22, 0x3a,
	0x0a, 0x20, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3b, 0x0a, 0x21, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0x9e, 0x01, 0x0a, 0x15, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x84, 0x01, 0x0a, 0x19, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x65, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x31, 0x2e, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x70,
	0x62, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x32, 0x2e, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x65, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x3a, 0x5a, 0x38, 0x68, 0x77, 0x5f, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f,
	0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_rawDescOnce sync.Once
	file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_rawDescData = file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_rawDesc
)

func file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_rawDescGZIP() []byte {
	file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_rawDescOnce.Do(func() {
		file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_rawDescData = protoimpl.X.CompressGZIP(file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_rawDescData)
	})
	return file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_rawDescData
}

var file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_goTypes = []interface{}{
	(*NumberDecompositionStreamRequest)(nil),  // 0: decompositionpb.NumberDecompositionStreamRequest
	(*NumberDecompositionStreamResponse)(nil), // 1: decompositionpb.NumberDecompositionStreamResponse
}
var file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_depIdxs = []int32{
	0, // 0: decompositionpb.StreamGreetingService.NumberDecompositionStream:input_type -> decompositionpb.NumberDecompositionStreamRequest
	1, // 1: decompositionpb.StreamGreetingService.NumberDecompositionStream:output_type -> decompositionpb.NumberDecompositionStreamResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_init() }
func file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_init() {
	if File_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberDecompositionStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberDecompositionStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_goTypes,
		DependencyIndexes: file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_depIdxs,
		MessageInfos:      file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_msgTypes,
	}.Build()
	File_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto = out.File
	file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_rawDesc = nil
	file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_goTypes = nil
	file_hw_streaming_number_decomposition_NumberDecompositionpb_decomposition_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StreamGreetingServiceClient is the client API for StreamGreetingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamGreetingServiceClient interface {
	NumberDecompositionStream(ctx context.Context, in *NumberDecompositionStreamRequest, opts ...grpc.CallOption) (StreamGreetingService_NumberDecompositionStreamClient, error)
}

type streamGreetingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamGreetingServiceClient(cc grpc.ClientConnInterface) StreamGreetingServiceClient {
	return &streamGreetingServiceClient{cc}
}

func (c *streamGreetingServiceClient) NumberDecompositionStream(ctx context.Context, in *NumberDecompositionStreamRequest, opts ...grpc.CallOption) (StreamGreetingService_NumberDecompositionStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StreamGreetingService_serviceDesc.Streams[0], "/decompositionpb.StreamGreetingService/NumberDecompositionStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamGreetingServiceNumberDecompositionStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamGreetingService_NumberDecompositionStreamClient interface {
	Recv() (*NumberDecompositionStreamResponse, error)
	grpc.ClientStream
}

type streamGreetingServiceNumberDecompositionStreamClient struct {
	grpc.ClientStream
}

func (x *streamGreetingServiceNumberDecompositionStreamClient) Recv() (*NumberDecompositionStreamResponse, error) {
	m := new(NumberDecompositionStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamGreetingServiceServer is the server API for StreamGreetingService service.
type StreamGreetingServiceServer interface {
	NumberDecompositionStream(*NumberDecompositionStreamRequest, StreamGreetingService_NumberDecompositionStreamServer) error
}

// UnimplementedStreamGreetingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStreamGreetingServiceServer struct {
}

func (*UnimplementedStreamGreetingServiceServer) NumberDecompositionStream(*NumberDecompositionStreamRequest, StreamGreetingService_NumberDecompositionStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method NumberDecompositionStream not implemented")
}

func RegisterStreamGreetingServiceServer(s *grpc.Server, srv StreamGreetingServiceServer) {
	s.RegisterService(&_StreamGreetingService_serviceDesc, srv)
}

func _StreamGreetingService_NumberDecompositionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NumberDecompositionStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamGreetingServiceServer).NumberDecompositionStream(m, &streamGreetingServiceNumberDecompositionStreamServer{stream})
}

type StreamGreetingService_NumberDecompositionStreamServer interface {
	Send(*NumberDecompositionStreamResponse) error
	grpc.ServerStream
}

type streamGreetingServiceNumberDecompositionStreamServer struct {
	grpc.ServerStream
}

func (x *streamGreetingServiceNumberDecompositionStreamServer) Send(m *NumberDecompositionStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _StreamGreetingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "decompositionpb.StreamGreetingService",
	HandlerType: (*StreamGreetingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NumberDecompositionStream",
			Handler:       _StreamGreetingService_NumberDecompositionStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hw_streaming_number_decomposition/NumberDecompositionpb/decomposition.proto",
}
